[global]
	auth_client_required = cephx
	auth_cluster_required = cephx
	auth_service_required = cephx
	cluster_network = 192.168.100.4/23
	fsid = b01c2578-0ec2-48bb-bb02-cbe9f5e220c1
	mon_allow_pool_delete = true
	mon_host =  192.168.100.4
	ms_bind_ipv4 = true
	ms_bind_ipv6 = false
	osd_pool_default_min_size = 2
	osd_pool_default_size = 3
	public_network = 192.168.100.4/23

[client]
	keyring = /etc/pve/priv/$cluster.$name.keyring

[client.crash]
	keyring = /etc/pve/ceph/$cluster.$name.keyring

[mon.server1]
	public_addr = 192.168.100.4

